name: 🚀 Deploy Monitoring (Prometheus + Grafana)

on:
  workflow_dispatch:

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and deploy monitoring stack
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Desplegar Prometheus y Grafana
          docker-compose pull prometheus grafana || true
          docker-compose up -d prometheus grafana
